#!/usr/bin/env python3
"""Generate synthetic PGHD submit fixtures for live PRE scalability tests.

The generated payloads are cryptographically valid for PRE signature checking:
each patient owns a P-256 PGHD signing key, each payload contains a SHA-256
hash of the synthetic encrypted PGHD bytes, and the hash is signed with ECDSA.

Important: random addresses generated by this script are not automatically
registered on IOTA. Live submit tests require patient_iota_address values that
exist in the DecMed smart contract, otherwise PRE will pass signature checking
and fail when it writes metadata to IOTA.
"""

from __future__ import annotations

import argparse
import base64
import dataclasses
import hashlib
import json
import os
import secrets
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, utils
from cryptography.hazmat.primitives.ciphers.aead import AESGCM


@dataclasses.dataclass(frozen=True)
class GeneratedPatient:
    index: int
    nik: str
    patient_id_hash: str
    patient_iota_address: str
    iota_key_pair: str
    seed_words: str
    medical_pre_public_key: str
    medical_pre_secret_seed: str
    pghd_pre_public_key: str
    pghd_pre_secret_seed: str
    pghd_private_key_pkcs8_base64: str
    pghd_public_key_der_base64: str
    registered_on_iota: bool
    registered_on_pre: bool


P256_N = int("ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551", 16)


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def run_json(command: list[str], *, label: str) -> Any:
    proc = subprocess.run(command, check=False, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(
            f"{label} failed with exit code {proc.returncode}\n"
            f"stdout: {proc.stdout}\nstderr: {proc.stderr}"
        )
    try:
        body = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"{label} returned non-JSON stdout: {proc.stdout}") from exc
    if not body.get("ok"):
        raise RuntimeError(f"{label} failed: {body.get('error')}")
    return body.get("data")


def post_json(url: str, payload: dict[str, Any], timeout: float) -> tuple[int, str]:
    import urllib.error
    import urllib.request

    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return response.status, response.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read().decode("utf-8", errors="replace")


def parse_env_file(path: Path | None) -> dict[str, str]:
    values: dict[str, str] = {}
    if path is None or not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, raw_value = stripped.split("=", 1)
        values[key.strip()] = raw_value.strip().strip('"').strip("'")
    return values


def load_reusable_patients(path: Path | None) -> dict[str, GeneratedPatient]:
    if path is None or not path.exists():
        return {}
    try:
        fixture = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"existing fixture is not valid JSON: {path}") from exc
    if fixture.get("schema_version") != "pre-stress-fixture-v1":
        return {}

    reusable: dict[str, GeneratedPatient] = {}
    for raw in fixture.get("patients", []):
        try:
            patient = GeneratedPatient(
                index=int(raw["index"]),
                nik=str(raw["nik"]),
                patient_id_hash=str(raw["patient_id_hash"]),
                patient_iota_address=str(raw["patient_iota_address"]),
                iota_key_pair=str(raw["iota_key_pair"]),
                seed_words=str(raw["seed_words"]),
                medical_pre_public_key=str(raw["medical_pre_public_key"]),
                medical_pre_secret_seed=str(raw["medical_pre_secret_seed"]),
                pghd_pre_public_key=str(raw["pghd_pre_public_key"]),
                pghd_pre_secret_seed=str(raw["pghd_pre_secret_seed"]),
                pghd_private_key_pkcs8_base64=str(raw["pghd_private_key_pkcs8_base64"]),
                pghd_public_key_der_base64=str(raw["pghd_public_key_der_base64"]),
                registered_on_iota=bool(raw.get("registered_on_iota", False)),
                registered_on_pre=bool(raw.get("registered_on_pre", False)),
            )
        except KeyError:
            continue
        reusable[patient.nik] = patient
    return reusable


def env_value(values: dict[str, str], key: str, default: str | None = None) -> str | None:
    return os.environ.get(key) or values.get(key) or default


def make_iota_config(values: dict[str, str], args: argparse.Namespace) -> dict[str, Any]:
    required = [
        "DECMED_PACKAGE_ID",
        "DECMED_ADDRESS_ID_OBJECT_ID",
        "DECMED_ADDRESS_ID_OBJECT_VERSION",
        "DECMED_PATIENT_ID_ACCOUNT_OBJECT_ID",
        "DECMED_PATIENT_ID_ACCOUNT_OBJECT_VERSION",
    ]
    missing = [key for key in required if not env_value(values, key)]
    if missing:
        raise RuntimeError(f"missing IOTA config values: {', '.join(missing)}")
    return {
        "iota_url": args.iota_url or env_value(values, "IOTA_URL", "http://127.0.0.1:9000"),
        "gas_station_base_url": args.gas_station_base_url
        or env_value(values, "GAS_STATION_BASE_URL", "http://127.0.0.1:9528/v1"),
        "gas_station_token": args.gas_station_token or env_value(values, "GAS_STATION_TOKEN", "token"),
        "package_id": env_value(values, "DECMED_PACKAGE_ID"),
        "address_id_object_id": env_value(values, "DECMED_ADDRESS_ID_OBJECT_ID"),
        "address_id_object_version": int(env_value(values, "DECMED_ADDRESS_ID_OBJECT_VERSION") or "0"),
        "hospital_id_metadata_object_id": env_value(values, "DECMED_HOSPITAL_ID_METADATA_OBJECT_ID", ""),
        "hospital_id_metadata_object_version": int(
            env_value(values, "DECMED_HOSPITAL_ID_METADATA_OBJECT_VERSION", "0") or "0"
        ),
        "hospital_personnel_id_account_object_id": env_value(
            values, "DECMED_HOSPITAL_PERSONNEL_ID_ACCOUNT_OBJECT_ID", ""
        ),
        "hospital_personnel_id_account_object_version": int(
            env_value(values, "DECMED_HOSPITAL_PERSONNEL_ID_ACCOUNT_OBJECT_VERSION", "0") or "0"
        ),
        "patient_id_account_object_id": env_value(values, "DECMED_PATIENT_ID_ACCOUNT_OBJECT_ID"),
        "patient_id_account_object_version": int(
            env_value(values, "DECMED_PATIENT_ID_ACCOUNT_OBJECT_VERSION") or "0"
        ),
        "hash_salt": env_value(values, "HASH_SALT"),
        "gas_budget": int(env_value(values, "IOTA_GAS_BUDGET", "100000000") or "100000000"),
        "gas_reserve_nanos": int(
            env_value(values, "IOTA_GAS_RESERVE_NANOS", "2000000000") or "2000000000"
        ),
        "gas_reserve_seconds": int(env_value(values, "IOTA_GAS_RESERVE_SECONDS", "300") or "300"),
    }


def bip39_seed(seed_words: str, passphrase: str) -> bytes:
    return hashlib.pbkdf2_hmac(
        "sha512",
        seed_words.strip().lower().encode("utf-8"),
        f"mnemonic{passphrase}".encode("utf-8"),
        2048,
        dklen=64,
    )


def derive_pre_seed(seed: bytes, label: str) -> str:
    return base64.b64encode(hashlib.sha256(seed + label.encode("utf-8")).digest()).decode("ascii")


def generate_pghd_keypair(seed: bytes) -> tuple[str, str]:
    material = hashlib.sha256(seed + b"decmed-pghd-ecdsa-v1").digest()
    private_scalar = (int.from_bytes(material, "big") % (P256_N - 1)) + 1
    private_key = ec.derive_private_key(private_scalar, ec.SECP256R1())
    private_key_der = private_key.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_key_der = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return (
        base64.b64encode(private_key_der).decode("ascii"),
        base64.b64encode(public_key_der).decode("ascii"),
    )


def register_on_pre(
    patient: GeneratedPatient,
    pre_base_url: str,
    timeout: float,
) -> None:
    status, body = post_json(
        pre_base_url.rstrip("/") + "/api/v1/pghd/patient",
        {
            "patient_id_hash": patient.patient_id_hash,
            "patient_iota_address": patient.patient_iota_address,
            "pghd_public_key": patient.pghd_public_key_der_base64,
            "pre_public_key": patient.medical_pre_public_key,
            "medical_pre_public_key": patient.medical_pre_public_key,
            "pghd_pre_public_key": patient.pghd_pre_public_key,
        },
        timeout,
    )
    if not 200 <= status <= 299:
        raise RuntimeError(
            f"PRE PGHD patient registration failed for {patient.patient_iota_address}: "
            f"HTTP {status}: {body}"
        )


def private_metadata(patient_id_hash: str) -> str:
    metadata = {
        "source": "pghd_pre_scalability_e2e",
        "patient_id_hash": patient_id_hash,
    }
    return base64.b64encode(json.dumps(metadata, separators=(",", ":")).encode("utf-8")).decode("ascii")


def generate_and_register_patient(
    index: int,
    nik: str,
    seed_words: str,
    iota_cli: str,
    crypto_cli: str,
    iota_config_json: str,
    pre_base_url: str,
    timeout: float,
    register_e2e: bool,
    allow_existing: bool,
    reusable_patient: GeneratedPatient | None = None,
) -> GeneratedPatient:
    if reusable_patient is not None:
        print(f"[INFO] reusing existing dummy account material: nik={nik}")
        patient = dataclasses.replace(reusable_patient, index=index)
    else:
        identity = run_json([iota_cli, "derive", seed_words, nik], label=f"derive IOTA identity {nik}")
        seed = bip39_seed(seed_words, nik)
        medical_pre_seed = derive_pre_seed(seed, "decmed-pre-medical-record-v1")
        pghd_pre_seed = derive_pre_seed(seed, "decmed-pre-pghd-v1")
        medical_pre_public_key = run_json(
            [crypto_cli, "public-key-from-seed", medical_pre_seed],
            label=f"derive medical PRE public key {nik}",
        )
        pghd_pre_public_key = run_json(
            [crypto_cli, "public-key-from-seed", pghd_pre_seed],
            label=f"derive PGHD PRE public key {nik}",
        )
        pghd_private_key, pghd_public_key = generate_pghd_keypair(seed)

        patient = GeneratedPatient(
            index=index,
            nik=nik,
            patient_id_hash=identity["id_hash"],
            patient_iota_address=identity["iota_address"],
            iota_key_pair=identity["iota_key_pair"],
            seed_words=seed_words,
            medical_pre_public_key=medical_pre_public_key,
            medical_pre_secret_seed=medical_pre_seed,
            pghd_pre_public_key=pghd_pre_public_key,
            pghd_pre_secret_seed=pghd_pre_seed,
            pghd_private_key_pkcs8_base64=pghd_private_key,
            pghd_public_key_der_base64=pghd_public_key,
            registered_on_iota=False,
            registered_on_pre=False,
        )

    if register_e2e:
        if not patient.registered_on_iota:
            try:
                run_json(
                    [
                        iota_cli,
                        "signup-and-publish-pghd-key",
                        iota_config_json,
                        patient.patient_id_hash,
                        private_metadata(patient.patient_id_hash),
                        patient.pghd_public_key_der_base64,
                        patient.patient_iota_address,
                        patient.iota_key_pair,
                    ],
                    label=f"signup and publish PGHD key {nik}",
                )
            except RuntimeError as exc:
                if allow_existing and (
                    "EAddressAlreadyRegistered" in str(exc)
                    or "EAccountAlreadyRegistered" in str(exc)
                    or "already registered" in str(exc).lower()
                ):
                    print(f"[INFO] patient already exists on IOTA, reusing deterministic test identity: {nik}")
                else:
                    raise
        patient = dataclasses.replace(patient, registered_on_iota=True)
        register_on_pre(patient, pre_base_url, timeout)
        patient = dataclasses.replace(patient, registered_on_pre=True)

    return patient


def sign_h_cipher(private_key_pkcs8_base64: str, h_cipher_bytes: bytes) -> str:
    private_key = serialization.load_der_private_key(
        base64.b64decode(private_key_pkcs8_base64),
        password=None,
    )
    signature = private_key.sign(
        h_cipher_bytes,
        ec.ECDSA(utils.Prehashed(hashes.SHA256())),
    )
    return base64.b64encode(signature).decode("ascii")


def make_payload(
    patient: GeneratedPatient,
    batch_index: int,
    records_per_batch: int,
    crypto_cli: str,
) -> dict[str, Any]:
    now_ms = int(time.time() * 1000)
    batch_id = f"pre-scale-p{patient.index:03d}-b{batch_index:04d}-{secrets.token_hex(4)}"
    pghd_plain = {
        "schema_version": "synthetic-pre-stress-v1",
        "batch_id": batch_id,
        "patient_iota_address": patient.patient_iota_address,
        "patient_test_nik": patient.nik,
        "collection_started_at": now_ms - records_per_batch * 60_000,
        "collection_ended_at": now_ms,
        "data_collected_period": {
            "start_timestamp": now_ms - records_per_batch * 60_000,
            "end_timestamp": now_ms,
        },
        "data_group": [
            {
                "measurement_type": "steps",
                "unit": "count",
                "source": "synthetic_pre_scalability",
                "device_type": "stress_fixture",
                "recording_method": "synthetic",
                "data_points": [
                    {
                        "timestamp": now_ms - (records_per_batch - i) * 60_000,
                        "value": 100 + patient.index + i,
                        "unit": "count",
                    }
                    for i in range(records_per_batch)
                ],
            }
        ],
    }

    plaintext = json.dumps(
        pghd_plain,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    aes_key = secrets.token_bytes(32)
    aes_nonce = secrets.token_bytes(12)
    enc_pghd_bytes = AESGCM(aes_key).encrypt(aes_nonce, plaintext, batch_id.encode("utf-8"))
    h_cipher_bytes = hashlib.sha256(enc_pghd_bytes).digest()
    wrapped_key_nonce = run_json(
        [
            crypto_cli,
            "encrypt-for-public-key",
            patient.pghd_pre_public_key,
            base64.b64encode(aes_key + aes_nonce).decode("ascii"),
        ],
        label=f"wrap PGHD AES key {batch_id}",
    )
    return {
        "batch_id": batch_id,
        "patient_id_hash": patient.patient_id_hash,
        "patient_iota_address": patient.patient_iota_address,
        "enc_pghd": base64.b64encode(enc_pghd_bytes).decode("ascii"),
        "h_cipher": h_cipher_bytes.hex(),
        "enc_aes_key_nonce": wrapped_key_nonce["ciphertext"],
        "capsule": wrapped_key_nonce["capsule"],
        "signature": sign_h_cipher(patient.pghd_private_key_pkcs8_base64, h_cipher_bytes),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate patient/material/payload fixtures for PRE scalability tests.",
    )
    parser.add_argument("--output", type=Path, default=Path("tmp/pghd-pre-stress-fixtures.json"))
    parser.add_argument(
        "--reuse-existing-fixture",
        type=Path,
        help="Reuse dummy account and cryptographic material from a previous fixture when NIK values match.",
    )
    parser.add_argument(
        "--accounts-output",
        type=Path,
        default=Path("tmp/pghd-pre-stress-dummy-accounts.txt"),
        help="Text file containing dummy NIK/PIN/seed words for manual Android login during scalability tests.",
    )
    parser.add_argument("--patients", type=int, default=20)
    parser.add_argument("--batches-per-patient", type=int, default=1)
    parser.add_argument("--records-per-batch", type=int, default=60)
    parser.add_argument("--nik-start", type=int, default=9_000_000_000_000_000)
    parser.add_argument("--seed-words", default="abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about")
    parser.add_argument("--dummy-pin", default="123456")
    parser.add_argument("--iota-cli", default="crypto/decmed-iota/target/debug/decmed_iota_cli")
    parser.add_argument("--crypto-cli", default="crypto/decmed-crypto/target/debug/decmed_crypto_cli")
    parser.add_argument("--env-file", type=Path, default=Path("client/pghd-android/.env"))
    parser.add_argument("--pre-base-url", default="http://127.0.0.1:4100")
    parser.add_argument("--iota-url")
    parser.add_argument("--gas-station-base-url")
    parser.add_argument("--gas-station-token")
    parser.add_argument("--timeout-seconds", type=float, default=120.0)
    parser.add_argument("--register-e2e", action="store_true")
    parser.add_argument("--generate-only", action="store_true")
    parser.add_argument("--allow-existing", action="store_true")
    return parser.parse_args()


def write_dummy_accounts_file(path: Path, patients: list[GeneratedPatient], pin: str, mode: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# DecMed PGHD PRE scalability dummy patient accounts",
        f"# generated_at={utc_now_iso()}",
        f"# mode={mode}",
        "# These accounts are dummy test material. Do not use them outside controlled tests.",
        "# Android login uses NIK + seed words to derive the IOTA identity; PIN is local session input.",
        "",
    ]
    for patient in patients:
        lines.extend(
            [
                f"[patient {patient.index + 1}]",
                f"nik={patient.nik}",
                f"pin={pin}",
                f"seed_words={patient.seed_words}",
                f"patient_iota_address={patient.patient_iota_address}",
                f"patient_id_hash={patient.patient_id_hash}",
                f"registered_on_iota={str(patient.registered_on_iota).lower()}",
                f"registered_on_pre={str(patient.registered_on_pre).lower()}",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    if args.register_e2e and args.generate_only:
        raise SystemExit("[FAIL] choose either --register-e2e or --generate-only, not both")
    if not Path(args.iota_cli).exists():
        raise SystemExit(f"[FAIL] IOTA CLI not found: {args.iota_cli}")
    if not Path(args.crypto_cli).exists():
        raise SystemExit(f"[FAIL] crypto CLI not found: {args.crypto_cli}")

    env_values = parse_env_file(args.env_file)
    iota_config = make_iota_config(env_values, args)
    iota_config_json = json.dumps(iota_config, separators=(",", ":"))
    reusable_patients = load_reusable_patients(args.reuse_existing_fixture)
    if reusable_patients:
        print(
            f"[INFO] loaded reusable dummy account material: "
            f"{len(reusable_patients)} patients from {args.reuse_existing_fixture}"
        )
    patients: list[GeneratedPatient] = []
    for index in range(args.patients):
        nik = f"{args.nik_start + index:016d}"
        print(f"[INFO] preparing patient {index + 1}/{args.patients}: nik={nik}")
        patients.append(
            generate_and_register_patient(
                index=index,
                nik=nik,
                seed_words=args.seed_words,
                iota_cli=args.iota_cli,
                crypto_cli=args.crypto_cli,
                iota_config_json=iota_config_json,
                pre_base_url=args.pre_base_url,
                timeout=args.timeout_seconds,
                register_e2e=args.register_e2e,
                allow_existing=args.allow_existing,
                reusable_patient=reusable_patients.get(nik),
            )
        )

    fixture = {
        "schema_version": "pre-stress-fixture-v1",
        "generated_at": utc_now_iso(),
        "mode": "registered_e2e" if args.register_e2e else "generate_only",
        "iota_config": {
            key: value
            for key, value in iota_config.items()
            if key not in {"gas_station_token"}
        },
        "pre_base_url": args.pre_base_url,
        "notes": [
            "Patients are generated from dummy NIK values and dummy cryptographic material.",
            "When mode=registered_e2e, patients have been signed up on DecMed SC and registered on PRE.",
            "Payloads use AES-GCM encrypted PGHD and Umbral-wrapped AES key material.",
        ],
        "patients": [],
    }

    total_payloads = args.patients * args.batches_per_patient
    generated_payloads = 0
    for patient in patients:
        payloads = []
        for batch_index in range(args.batches_per_patient):
            payloads.append(make_payload(patient, batch_index, args.records_per_batch, args.crypto_cli))
            generated_payloads += 1
            if generated_payloads == 1 or generated_payloads % 10 == 0 or generated_payloads == total_payloads:
                print(f"[INFO] generated payloads {generated_payloads}/{total_payloads}")
        fixture["patients"].append(
            {
                **dataclasses.asdict(patient),
                "pghd_public_key": patient.pghd_public_key_der_base64,
                "payloads": payloads,
            }
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(fixture, indent=2), encoding="utf-8")
    mode = "registered_e2e" if args.register_e2e else "generate_only"
    write_dummy_accounts_file(args.accounts_output, patients, args.dummy_pin, mode)
    print("[PASS] PRE stress fixtures generated")
    print(f"[INFO] output={args.output}")
    print(f"[INFO] accounts_output={args.accounts_output}")
    print(f"[INFO] patients={args.patients}")
    print(f"[INFO] nik_range={patients[0].nik}..{patients[-1].nik}")
    print(f"[INFO] batches={args.patients * args.batches_per_patient}")
    print(f"[INFO] mode={mode}")


if __name__ == "__main__":
    main()
